---
- name: Install zsh
  become: true
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Change user's shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/zsh

- name: Install Brew and Starship
  ansible.builtin.include_role:
    name: ctorgalson.linuxbrew
  vars:
    ansible_become: true

- name: Create .zsh directory
  ansible.builtin.file:
    path: "/home/{{ username }}/.zsh"
    state: directory
    mode: '0755'

- name: Clone zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "/home/{{ username }}/.zsh/zsh-autosuggestions"

- name: Clone zsh-syntax-highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ username }}/.zsh/zsh-syntax-highlighting"

- name: Update .zshrc file
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/.zshrc.j2"
    dest: "/home/{{ username }}/.zshrc"
    owner: "{{ username }}"
    mode: '0744'
